name: ghaskui
version: 0.1.0.0
synopsis: A native cross-platform GUI framework for Haskell
description: GHaskUI aims to provide a way to build native GUIs in Haskell using only the base library and FFI
category: Graphics
author: Thundron <la@thundron.dev>
maintainer: Thundron <la@thundron.dev>
copyright: Thundron <la@thundron.dev>
license: Apache-2.0
homepage:    https://github.com/thundron/ghaskui#readme
bug-reports: https://github.com/thundron/ghaskui/issues

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - ScopedTypeVariables
    - RecordWildCards
    - GADTs
    - ConstraintKinds
    - MultiParamTypeClasses
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
  dependencies:
    - base >= 4.14 && < 5
  exposed-modules:
    - GHaskUI
    - GHaskUI.Platform.Windows
    - GHaskUI.Core

dependencies:
  - base >= 4.14 && < 5

executables:
  calculator:
    main:                Main.hs
    source-dirs:         examples/calculator
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ghaskui
      - base >= 4.14 && < 5
