name: calculator-example
version: 0.1.0.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -threaded 
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base >= 4.14 && < 5
  - ghaskui 

executables:
  calculator:
    main: Main.hs
    source-dirs: . # Source is in the current directory
    dependencies:
      - base >= 4.14 && < 5
      - ghaskui
